### ISSUE TITLE
Comprobar configuración de los polls

### ISSUE THREAD

**Issue by angrykoala** [oslugr/polleitor#13]
Hay que revisar como configurar los polls.

Usar script y jsonp no termina de convencerme, a lo mejor usando objetos con class o cosas asi puede hacerse mas facil y mejor

**Comment by JJ** [comment]
¿Cómo se te ocurre?

**Comment by angrykoala** [comment]
A ver, que hacer se podra hacer, pero quizas con class="pregunta-1" o algo asi conseguimos lo mismo y mas facil no?

**Comment by JJ** [comment]
Eso necesitaría un poco de magia HTML5 que se me escapa, la verdad. Para empezar, tendría que ser class="pregunta" data-id='1'. Para seguir, tendría que haber algún JS que fuera recorriendo el DOM y sacándolo, ¿no?

**Comment by angrykoala** [comment]
Algo asi, no soy demasiado mago del html aun, pero sospecho que es mas facil (y eficiente) tener un script que busque todos los objetos pregunta y los vaya "rellenando" que no pedir scripts a la API. Además, nos sale una API un pelín mas estándar con JSON plano

Lo mas elegante (y poser) sería ya usar webcomponents, pero yo al menos no se como hacerlos aun y no hay tanto tiempo

**Comment by JJ** [comment]
¿Rollo tipo polymer?

**Comment by angrykoala** [comment]
Si, rollo polymer, si se quisiera poner comercial seria ideal:

``` html
<poll id=2 url="angry.koala" ....>
</poll>
```

Pero andamos un pelín justos de tiempo y es matar moscas a cañonazos

**Comment by JJ** [comment]
Bueno, no hace falta inventar una etiqueta, pero si hay alguna forma fácil de hacer lo que dices...

**Comment by angrykoala** [comment]
creo que lo mas facil es lo que has dicho:

``` html
<div class="poll" id=2>
</div>
<div class="poll" id=1>
</div>

<script>
$('.poll').function(){loadpoll()}
</script>
```

**Comment by JJ** [comment]
Sí, módulo que en function habrá que acceder a los atributos y loadpoll llamarse con los mismos atributos. 
En todo caso estoy mirando y esto es rollo WebComponents. Pero para esta versión yo creo que con eso se tira.

**Comment by angrykoala** [comment]
Si, luego si sale chulo miro lo de polymer, que quiero aprenderlo. pero de esta forma se puede hacer todo relativamente eficiente y asincrono, de hecho se podria hacer a tiempo real en un futuro (sooockets)

**Comment by angrykoala** [comment]
`<div class="poll" data-poll-name="test">` funciona razonablemente

**Comment by JJ** [comment]
Genial...

2016-06-27 10:46 GMT+02:00 Andrés notifications@github.com:

> <div class="poll" data-poll-name="test"> funciona razonablemente
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/oslugr/polleitor/issues/13#issuecomment-228687331,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAAB9MaMrji5Vgrnb9RsLQ8k-UEajsUPks5qP43ngaJpZM4I8sy4
> .

## 

JJ

**Comment by angrykoala** [comment]
Unicamente falta ver como hacer funcionar bien los formularios #14

**Comment by germaaan** [comment]
Con #3, #14 y #16 resueltos, esto se podría cerrar, ¿no?

**Comment by angrykoala** [comment]
Supongo
