### ISSUE TITLE
Comprobar integración con slides.js o lo que sea

### ISSUE THREAD

**Issue by angrykoala** [oslugr/polleitor#15]
habría que revisar como funciona esto con una presentación real

**Comment by JJ** [comment]
De eso me encargo yo cuando me deslíe un poco

2016-06-28 9:38 GMT+02:00 Andrés notifications@github.com:

> habría que revisar como funciona esto con una presentación real
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/oslugr/polleitor/issues/15, or mute the thread
> https://github.com/notifications/unsubscribe/AAAB9P9FbFH6VVvSNRJLNqIZqJj-uSOUks5qQM9cgaJpZM4I_0rm
> .

## 

JJ

**Comment by angrykoala** [comment]
ok

**Comment by JJ** [comment]
![screenshot from 2016-06-30 08 09 50](https://cloud.githubusercontent.com/assets/500/16478449/0c809a90-3e9a-11e6-8841-f68e70543ea7.png)
No va con reveal.js
