### ISSUE TITLE
No funciona el envío de respuestas

### ISSUE THREAD

**Issue by JJ** [oslugr/polleitor#16]
Para empezar, en el código había un POST en vez de un PUT. Pero es que con el PUT tampoco funciona.

**Comment by germaaan** [comment]
Lo habíamos cambiado a POST para probar a enviar las respuestas desde un formulario que se genera en el propia página, pero todavía no está terminado.

**Comment by JJ** [comment]
Ya lo he vuelto a cambiar a PUT.

El 28 de junio de 2016, 19:24, German Martinez notifications@github.com
escribió:

> Lo habíamos cambiado a POST para probar a enviar las respuestas desde un
> formulario que se genera en el propia página, pero todavía no está
> terminado.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/oslugr/polleitor/issues/16#issuecomment-229119894,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAAB9HRcTVw5A7qbznzNp8LdMQFv87pYks5qQVjDgaJpZM4JAVLk
> .

## 

JJ
