### ISSUE TITLE
Trabajar sobre el frontend

### ISSUE THREAD

**Issue by JJ** [oslugr/polleitor#19]
Que haya algún tipo de cambio en el display cuando se recibe la respuesta: que se muestre el número de respuestas, por ejemplo o simplemente que se "disablee" el botón.

**Comment by angrykoala** [comment]
Vas a usar d3js o algo más sencillo y rapido (por ejemplo highcharts+jquery)?

**Comment by JJ** [comment]
Voy a mirar highcharts

**Comment by JJ** [comment]
Lo único que quedaría es poner los botones un poco más bonicos, pero yo diría que la funcionalidad está ya.

**Comment by germaaan** [comment]
Integrar un framework solo por eso sería matar moscas a cañonazos, pero se puede buscar el estilo que tienen para esos elementos en Foundation, Kube o aquelotroframeworkquenodebesernombrado.

**Comment by JJ** [comment]
:-)

El 1 de julio de 2016, 8:21, German Martinez notifications@github.com
escribió:

> Integrar un framework solo por eso sería matar moscas a cañonazos, pero se
> puede buscar el estilo que tienen para esos elementos en Foundation, Kube o
> aquelotroframeworkquenodebesernombrado.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/oslugr/polleitor/issues/19#issuecomment-229863499,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAAB9B2eyOgPytNjURAFRjr_Pl_VMQfbks5qRLH_gaJpZM4JAXGB
> .

## 

JJ
