### ISSUE TITLE
Cerrar rama dev

### ISSUE THREAD

**Issue by angrykoala** [oslugr/polleitor#20]
la rama dev ya no se esta usando, la cierro?

**Comment by JJ** [comment]
Sí

2016-06-29 10:07 GMT+02:00 Andrés notifications@github.com:

> la rama dev ya no se esta usando, la cierro?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/oslugr/polleitor/issues/20, or mute the thread
> https://github.com/notifications/unsubscribe/AAAB9AyfTfF6xb8tMSebeJHiAJflOEgzks5qQielgaJpZM4JA32O
> .

## 

JJ
