### ISSUE TITLE
Configurar PaaS y desplegar 

### ISSUE THREAD

**Issue by JJ** [oslugr/polleitor#29]
Probar BlueMix, Heroku u OpenShift

**Comment by germaaan** [comment]
Heroku yo lo veo quizás el más inestable teniendo en cuenta que es una base de datos en memoria.

**Comment by angrykoala** [comment]
tiene backup a disco, creo que cualquiera sirve

**Comment by JJ** [comment]
Pero no la "tira", simplemente la "duerme" mínimo 3 horas al día. Sería
para un rato, de todas formas...

2016-06-30 16:59 GMT+02:00 Andrés notifications@github.com:

> tiene backup a disco, creo que cualquiera sirve
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/oslugr/polleitor/issues/29#issuecomment-229685043,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAAB9LIiam4ceouzS7DuNwxp8ZlFKaB3ks5qQ9nPgaJpZM4JCECT
> .

## 

JJ

**Comment by angrykoala** [comment]
En mi experiencia heroku si tiene el problema de qu ela BDD en memoria desaparece y hay que "recargarla" cuando se duerme. Eso puede tener consecuencias en peridda de datos (en teoria pocos porque loki vuelca constantemente los datos) pero con openshift pasa lo mismo
