### ISSUE TITLE
¿Subir paquete a npm?

### ISSUE THREAD

**Issue by angrykoala** [oslugr/polleitor#30]
Crear un paquete npm funcional y subirlo al repositorio

**Comment by JJ** [comment]
Si tú quieres... Habría que poner bien las licencias en todos los ficheros
antes y por supuesto documentar.

2016-06-30 13:32 GMT+02:00 Andrés notifications@github.com:

> Crear un paquete npm funcional y subirlo al repositorio
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/oslugr/polleitor/issues/30, or mute the thread
> https://github.com/notifications/unsubscribe/AAAB9PUN4kdVLuOuJdQDSHzAOU6e4gRFks5qQ6lWgaJpZM4JCEFx
> .

## 

JJ

**Comment by angrykoala** [comment]
Documentado y licenciado en todos los ficheros ya.

Lo proponia como opción una vez este todo ya estable y bonico

**Comment by angrykoala** [comment]
Closed due to inactivity
