### ISSUE TITLE
Añadir metadatos a los resultados

### ISSUE THREAD

**Issue by JJ** [oslugr/polleitor#34]
Sacados del user-agent. Como mínimo, OS, navegador, cosas así.

**Comment by angrykoala** [comment]
A que resultados exactamente?

**Comment by JJ** [comment]
A los de las encuestas..

**Comment by angrykoala** [comment]
Que al pedir los resultados de las encuestas puedas ver una lista de votos en funcion de los parametros de user agent?

Por ejemplo:

```
{
...
SO:{
windows: [resultados],
linux:[resultados]
---
}
```

**Comment by angrykoala** [comment]
Si estas usando los logs, una solucion facil es incluir los metadatos en el propio log del PUT

**Comment by JJ** [comment]
sí, pero para eso tienes que pasar esos resultados...

**Comment by angrykoala** [comment]
Ahora mismo, con cada PUT la terminal devuelve:

``` JSON
{"poll":"asignatura","id":"1","answer":"1","updated":0,"failed":1,"browser":"Chromium","os":"Ubuntu"}
```

no se si te sirve o quieres almacenarlos también en el loki

**Comment by JJ** [comment]
No sólo en los logs, también en memoria

**Comment by angrykoala** [comment]
OK, pero eso hay que ver como los almacenamos, como respuestas respecto a tipo de buscador/sistema?

**Comment by JJ** [comment]
junto con la respuesta. Luego ya se procesará como sea.

2016-07-14 12:35 GMT+02:00 Andrés notifications@github.com:

> OK, pero eso hay que ver como los almacenamos, como respuestas respecto a
> tipo de buscador/sistema?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/oslugr/polleitor/issues/34#issuecomment-232628406,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAAB9Pl8XbbQ4FYQkjU-2tfP4RbeDz2Nks5qVhDkgaJpZM4JC5Dj
> .

## 

JJ

**Comment by angrykoala** [comment]
Ok, voy a probar a ver

**Comment by angrykoala** [comment]
Metadatos añadidos, AVISO: Los polls.json de esta nueva version ya no son compatibles.

Se almacenan las respuestas como un par {id, meta}.

de momento los metadatos son el agente entero, pero es posible cambiar los datos alamacenados en el método `answerQuestion: function(poll, id, answer, token,agent)`

**Comment by JJ** [comment]
Gracias, Andrés.

El 14 de julio de 2016, 12:51, Andrés notifications@github.com escribió:

> Metadatos añadidos, AVISO: Los polls.json de esta nueva version ya no son
> compatibles.
> 
> Se almacenan las respuestas como un par {id, meta}.
> 
> de momento los metadatos son el agente entero, pero es posible cambiar los
> datos alamacenados en el método answerQuestion: function(poll, id,
> answer, token,agent)
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/oslugr/polleitor/issues/34#issuecomment-232631567,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAAB9HLO3o-U_D0xDfwmvi8OrLiNE-cuks5qVhS0gaJpZM4JC5Dj
> .

## 

JJ
