### ISSUE TITLE
Usar tokens para autenticación en el API

### ISSUE THREAD

**Issue by JJ** [oslugr/polleitor#4]
Simplemente para que no se hagan peticiones a lo loco. Lo suyo sería implementar una ruta que proporcione el token y comprobar que el token está asociado a user-agent o algo así, ¿no?

**Comment by germaaan** [comment]
Por todo lo que estoy viendo, sin entrar en cosas demasiado complejas lo normal es usar "JSON Web Token" con una autenticación basada en usuario/contraseña, se podría usar algo así, pero cambiando en todo caso lo de la autenticación de usuario/contraseña por la información "user-agent". Puede que así fuera un proceso más ágil incluso.

**Comment by JJ** [comment]
:-)

El 19 de junio de 2016, 14:42, German Martinez notifications@github.com
escribió:

> Por todo lo que estoy viendo, sin entrar en cosas demasiado complejas lo
> normal es usar "JSON Web Token" con una autenticación basada en
> usuario/contraseña, se podría usar algo así, pero cambiando en todo caso lo
> de la autenticación de usuario/contraseña por la información "user-agent".
> Puede que así fuera un proceso más ágil incluso.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/oslugr/polleitor/issues/4#issuecomment-226995371, or mute
> the thread
> https://github.com/notifications/unsubscribe/AAAB9LjR0bfMmoAXEbc9P4RJQWUWZllJks5qNTkogaJpZM4I47ll
> .

## 

JJ

**Comment by angrykoala** [comment]
Autenticación básica hecha, falta refinar

**Comment by germaaan** [comment]
52b21f1cb42c4d980edaf040d1f6dd5d91910462

**Comment by germaaan** [comment]
Ahora mismo no permite votar dos veces al mismo usuario:

curl -X PUT http://localhost:3000/test/1/1
{"status":"OK","ok":true,"poll":"test","pregunta":"1"}

curl -X PUT http://localhost:3000/test/1/1
{"status":"FAIL","ok":false,"poll":"test","pregunta":"1"}

**Comment by JJ** [comment]
Genial, buen trabajo.

2016-06-24 11:45 GMT+02:00 German Martinez notifications@github.com:

> Ahora mismo no permite votar dos veces al mismo usuario:
> 
> curl -X PUT http://localhost:3000/test/1/1
> {"status":"OK","ok":true,"poll":"test","pregunta":"1"}
> 
> curl -X PUT http://localhost:3000/test/1/1
> {"status":"FAIL","ok":false,"poll":"test","pregunta":"1"}
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/oslugr/polleitor/issues/4#issuecomment-228304025, or mute
> the thread
> https://github.com/notifications/unsubscribe/AAAB9LLMAztX2WU7TfBjZV1Bn0vGHeWfks5qO6ckgaJpZM4I47ll
> .

## 

JJ

**Comment by angrykoala** [comment]
Comprobado en los tests que no permita votar 2 veces
