### ISSUE TITLE
¿Funciona npm doc?

### ISSUE THREAD

**Issue by JJ** [oslugr/polleitor#40]
Debería generar la documentación y lo que hace es abrir un navegador con el README.md

**Comment by angrykoala** [comment]
`npm doc` redirecciona a la direccion de home del package.json `"homepage": "https://github.com/oslugr/polleitor#readme"`  (reconozco que no sabia yo esto, es cosa del npm)

Para ejecutar el script generador de documentacion ejecutar `npm run doc`

Ojo!, la documentacion se publica automaticamente en gh pages con ese comando
