### ISSUE TITLE
Generar documentación también para código cliente

### ISSUE THREAD

**Issue by JJ** [oslugr/polleitor#41]
Que parece que el groc no le hace caso.

**Comment by angrykoala** [comment]
El archivo .groc.json tiene la configuracion de archivos.

Solo he generado la documentacion servidor. Espero que el cliente tenga algo de comentarios, porque si no dificil documentarlo.

**Comment by JJ** [comment]
¡Se cierra con un commit!

2016-07-05 10:32 GMT+02:00 Andrés notifications@github.com:

> Closed #41 https://github.com/oslugr/polleitor/issues/41.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/oslugr/polleitor/issues/41#event-712688994, or mute
> the thread
> https://github.com/notifications/unsubscribe/AAAB9NUHR4HbDrJ73uvzaBkEoKcAQzj_ks5qShaNgaJpZM4JDTUD
> .

## 

JJ

**Comment by angrykoala** [comment]
Es que he tenido algun problemilla con los commits a gh-pages y se me paso...
