### ISSUE TITLE
Problemas con despliegue en heroku

### ISSUE THREAD

**Issue by JJ** [oslugr/polleitor#43]
Hay varios problemas con heroku. El primero y principal es que en heroku no se mantienen las aplicaciones en memoria todo el tiempo, se rearrancan, con lo que los resultados se pierden. Además, no se puede acceder a los logs ni hay almacenamiento permanente, así que la persistencia de la BD también se pierde. Con lo que no sé si es una buena idea desplegar en heroku. Se podría usar otro PaaS, Openshift por ejemplo, como referencia.

**Comment by angrykoala** [comment]
El sistema deberia funcionar bien al rearrancar, pero si heroku tira los archivos generados (donde esta la base de datos) poco se puede hacer.

Se puede probar a usar mongodb en lugar de lokijs, creo que a la larga nos quita problemas creo yo.

**Comment by JJ** [comment]
Bueno, la idea es que se pueda reconstruir las respuestas a partir de log
usando Papertrail o algo similar, que es más permanente...

**Comment by angrykoala** [comment]
mmm, veo mas facil simplemente generar un log a partir de la db o algo asi, pero bueno, ya lo vemos

**Comment by JoaquinJimenezGarcia** [comment]
Con CLEAR DB, una base de datos SQL, podéis hacer persistencia; ya que esta no se borra. Es un add-on que tenéis que instalar. Espero que os sirva. 

PD: no se borran los registros en estas, los archivos de fuera sí

**Comment by JJ** [comment]
¿Hay algún sitio donde se pueda usar? ¿Un tier gratuito?

**Comment by JoaquinJimenezGarcia** [comment]
Lo tenéis que añadir directamente como Add-On a la cuenta de Heroku (es gratuito, aunque te pide que tengas registrada la tarjeta) y con algún motor como Workbench, accedéis a ella para manipularla.

En este video queda muy claro todo (fue con el que yo lo conseguí hace un par de días): https://www.youtube.com/watch?v=iRgSQTmA-N4&t=460s

**Comment by JJ** [comment]
Muchas gracias.
