### ISSUE TITLE
Problemas con el PUT

### ISSUE THREAD

**Issue by JJ** [oslugr/polleitor#44]
Tal como está diseñado, se pasa la información en un JSON. El problema es que como la BD no es permanente, el JSON no aparece en los logs con lo que es imposible recuperarlo. En resumen: que no tengo ni idea de qué resultados tuvo la _poll_ de ayer durante la charla. Creo que no sería tan complicado cambiarlo para que la petición PUT contuviera toda la info en un URL.

**Comment by angrykoala** [comment]
la BDD si es permanente. Se supone que si no hubo problemas se debería guardar en el archivo .json, lo revisare a ver.

El Put no debería cambiarse, se pueden logear los resultados aparte de todas formas

**Comment by JJ** [comment]
Sí, pero es que los archivos en Heroku tampoco son permanentes, se borran a
las 24h.

2016-07-10 11:47 GMT+02:00 Andrés notifications@github.com:

> la BDD si es permanente. Se supone que si no hubo problemas se debería
> guardar en el archivo .json, lo revisare a ver
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/oslugr/polleitor/issues/44#issuecomment-231580235,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAAB9INUpvojTyvB8adx-V83waoEQU93ks5qUL_IgaJpZM4JIjQ6
> .

## 

JJ

**Comment by angrykoala** [comment]
Eso explica muchas cosas...

No serie mejor pasar a mongo en lugar de loki? casi nos quitamos problemas
