### ISSUE TITLE
Diseñar rutas para el servidor

### ISSUE THREAD

**Issue by JJ** [oslugr/polleitor#5]
Las rutas incluirán siempre un JSON token (o lo que sea) como uno de sus parámetros. Serán
- `GET /:ID`

Token inicial para el resto de la sesión o para el usuario. Se puede almacenar en un cookie. El Token será diferente por ID y por IP. Devolverá también un JSON con, aparte del Token, las preguntas y respuestas.
- `PUT /:token/:id/:respuesta`

Servirá para almacenar la respuesta. Devolverá los resultados actuales de la encuesta.
- `GET /:token/:id`

Devolverá los resultados de la encuesta con el ID concreto.

No sé si debería haber algo más. Yo creo que con esos tres debería ser suficiente, ¿no?

**Comment by germaaan** [comment]
Con ea157f482c175e8bc61237d59d09aac0a3706b9e he añadido la gestión de sesiones, así se puede pasar el token entre las diferentes rutas sin necesidad de cookies (lo que así evita tener que poner el mensaje de que acepten las cookies).

Así que se podría usar también el valor de token en la sesión para almacenar la respuesta en la base de datos sin que sea necesario pasarlo por parámetro.

**Comment by JJ** [comment]
Pero ¿si abren y cierran el navegador, podrán "votar" otra vez?

**Comment by germaaan** [comment]
Pues seguramente, en ese caso no queda otra que almacenarlo en el ordenador del cliente o pasar algo más identificador como la MAC.

**Comment by germaaan** [comment]
Voy a probar con el `session-file-store` para añadirle persistencia.

**Comment by JJ** [comment]
Déjalo, no merece la pena, creo. Dejamos el user-agent como cookie.
https://www.sans.org/reading-room/whitepapers/malicious/user-agent-field-analyzing-detecting-abnormal-malicious-organization-33874

**Comment by angrykoala** [comment]
cambiado :id por :poll para mejor claridad. Algunas rutas cambiadas, pero siguen la misma estructura base. Documentar en el readme las rutas y explicarlas en la tabla

**Comment by angrykoala** [comment]
Rutas diseñadas, especificadas en el readme.md
